# Generated by Django 3.1.1 on 2020-09-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
