# Generated by Django 3.1.1 on 2020-09-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200918_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='due_date',
            new_name='entry_date',
        ),
    ]
