# Generated by Django 3.1.1 on 2020-09-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200919_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='daily_rate',
            new_name='price',
        ),
    ]
